language: python

python:
  - '3.6'

services:
  - mysql

matrix:
  include:
    - os: osx
      language: generic
      sudo: required

env:
  - DJANGO=1.11 DB=mysql

before_install:
  - brew update       
  - brew install python3
  - virtualenv env -p python3
  - source env/bin/activate
  - brew install mecab
  - brew install mecab-ipadic
  - brew install mysql

install:
  - pip install -r requirements.txt

before_script:
  - mysql.server start
  - mysql -u root
  - mysql -e "select * from mysql.user;"
  - mysql -e "insert into mysql.user (Host, User, Password) values ('127.0.0.1', 'root', PASSWORD('guujin0120'));"
  - mysql -e "select * from mysql.user;"
  - mysql -e "grant all privileges on *.* to 'root'@'127.0.0.1' with grant option;"
  - mysql -e "flush privileges"

script:
  - cd gunosychallenge
  - python manage.py test
