language: python

python:
  - '3.6'

matrix:
  include:
    - os: osx
      sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then

        brew update;
        brew install python3;
        python3 -m venv venv;
        source venv/bin/activate;

install:
  - pip install -r requirements.txt

script:
  - cd gunosychallenge
  - python manage.py test
