language: python

python:
  - '3.6'

services:
  - mysql

matrix:
  include:
    - os: osx
      language: generic
      sudo: required

env:
  - DJANGO=1.11 DB=mysql

before_install:
  - brew update       
  - brew install python3
  - python3 -m venv env
  - source env/bin/activate
  - brew install mysql
  - brew install mecab
  - brew install mecab-ipadic
  - git clone --depth 1 git@github.com:neologd/mecab-ipadic-neologd.git
  - ./mecab-ipadic-neologd/bin/install-mecab-ipadic-neologd -y -n

install:
  - pip install -r requirements.txt

before_script:
  - flake8 --exclude=migrations,settings.py gunosynews gunosychallenge
  - mysql.server start
  - mysql -e "create database travis_ci_db;" -u root --host=127.0.0.1
  - mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'travis';" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;" -u root

script:
  - python gunosynews/gunosynews/tests/scrapy_test.py
  - cd gunosychallenge
  - python manage.py test
