language: python

python:
  - '3.6'

services:
  - mysql

matrix:
  include:
    - os: osx
      language: generic
      sudo: required

env:
  - DJANGO=1.11 DB=mysql

before_install:
  - brew update       
  - brew install python3
  - virtualenv env -p python3
  - source env/bin/activate
  - brew install mecab
  - brew install mecab-ipadic
  - brew install mysql

install:
  - pip install -r requirements.txt

before_script:
  - mysqld_safe --skip-grant-tables &
  - mysql -u root --host=127.0.0.1
  - mysql -e "use mysql;"
  - mysql -e "truncate table user;"
  - mysql -e "grant all privileges on *.* to 'root'@'localhost' identified by 'guujin0120' with grant option;"
  - mysql -e "quit;"
  - mysql.server start
  
script:
  - cd gunosychallenge
  - python manage.py test
