language: python

python:
  - '3.6'

services:
  - mysql

matrix:
  include:
    - os: osx
      language: generic
      sudo: required

before_install:
  - brew update       
  - brew install python3
  - virtualenv env -p python3
  - source env/bin/activate
  - brew install mecab
  - brew install mecab-ipadic
  - brew install mysql
  - mysql.server start
  - mysql -e 'CREATE DATABASE myapp_test;'

install:
  - pip install -r requirements.txt

script:
  - cd gunosychallenge
  - python manage.py test
