language: python

python:
  - '3.6'

matrix:
  include:
    - os: osx
      language: generic

before_install:
  - brew update       
  - brew install python3
  - virtualenv env -p python3
  - source env/bin/activate
  - sudo apt install libmecab-dev

install:
  - pip install -r requirements.txt

script:
  - cd gunosychallenge
  - python manage.py test
