# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clf', '0003_auto_20170705_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
