# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clf', '0004_remove_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
