# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clf', '0006_auto_20170713_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
